# Generated by Django 4.1 on 2023-10-02 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("doses", models.IntegerField(default=1)),
                (
                    "pub_data",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Publicacao",
                    ),
                ),
                ("tempo_prep", models.PositiveSmallIntegerField(default=1)),
                (
                    "grau_dificuldade",
                    models.CharField(
                        choices=[
                            ("Fácil", "Fácil"),
                            ("Médio", "Médio"),
                            ("Dificil", "Dificil"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Carne", "Carne"),
                            ("Peixe", "Peixe"),
                            ("Vegetariano/Vegan", "Vegetariano/Vegan"),
                            ("Salada", "Salada"),
                            ("Sobremesa", "Sobremesa"),
                            ("Entrada", "Entrada"),
                        ],
                        max_length=100,
                    ),
                ),
                ("calorias", models.PositiveIntegerField(default=1)),
                ("modo_prep", models.CharField(max_length=4000)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="recipe_image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="foto_perfil"),
                ),
                (
                    "descricao_pessoal",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("total_comentarios", models.IntegerField(default=0)),
                ("total_avaliacoes", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingrediente", models.CharField(max_length=200)),
                (
                    "quantidade",
                    models.CharField(
                        choices=[
                            ("Unidades", "Unidades"),
                            ("g", "g"),
                            ("Kg", "Kg"),
                            ("mL", "mL"),
                            ("L", "L"),
                            ("q.b.", "q.b."),
                        ],
                        max_length=100,
                    ),
                ),
                ("unidade", models.PositiveIntegerField(default=0)),
                (
                    "extra_opcional",
                    models.CharField(default="", max_length=400, null=True),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipe.receita"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.CharField(default="", max_length=100000)),
                (
                    "com_data",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data do Comentario",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipe.receita"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default="",
                    ),
                ),
                (
                    "ava_data",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data da Avaliacao",
                    ),
                ),
                (
                    "receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipe.receita"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "receita")},
            },
        ),
    ]
