# Generated by Django 4.1 on 2023-10-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_remove_perfil_id_alter_perfil_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="descricao_pessoal",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
