# Generated by Django 4.1 on 2023-10-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_comentario_classificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="classificacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipe.classificacao"
            ),
        ),
    ]
