# Generated by Django 4.1 on 2023-10-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_alter_comentario_classificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="extra_opcional",
            field=models.CharField(default="", max_length=400),
        ),
    ]
