# Generated by Django 4.1 on 2023-10-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0009_alter_ingrediente_extra_opcional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="extra_opcional",
            field=models.CharField(blank=True, default="", max_length=400, null=True),
        ),
    ]
