# Generated by Django 4.1 on 2023-10-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0011_alter_ingrediente_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="unidade",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
