# Generated by Django 4.1 on 2023-10-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0012_alter_ingrediente_unidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingrediente",
            name="unidade",
            field=models.FloatField(default=0),
        ),
    ]
